### ISSUE TITLE
Broken markup when <font> tag is used

### ISSUE THREAD

**Issue by chrisprog20** [TYPO3/html-sanitizer#49] opened 2021-08-25 12:43 UTC
TYPO3-Version: 9.5.30

Today we had an issue with a content element of type "table". The editor had there a `<font color="#f00">` tag used to highlight specific parts of the words in a cell. Since the update from 9.5.28 to 9.5.30 this behaviour has been occurred. We now fixed it by changing `<f:format.html><f:format.nl2br>{cell}</f:format.nl2br></f:format.html>` to `<f:format.raw><f:format.nl2br>{cell}</f:format.nl2br></f:format.html>` acoording to the advice given in [https://github.com/TYPO3/html-sanitizer/issues/23](https://github.com/TYPO3/html-sanitizer/issues/23).

Kind regards!

**Comment by ohader** [comment] 2021-08-25 13:27
Duplicate of issue #40 and PRs #41 and 42

**Closed by ohader** 2021-08-25 13:27 UTC
